databases:
  - name: gamerune-db
    plan: free
    databaseName: gamerune
    user: gamerune

services:
  - type: web
    name: game-lister-backend
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RAWG_API_KEY
        sync: false
      - key: JWT_KEY
        sync: false
      - key: Jwt__Issuer
        value: gamerune
      - key: Jwt__Audience
        value: gamerune-frontend
      - key: ConnectionStrings__Default
        fromDatabase:
          name: gamerune-db
          property: connectionString
